version: '3.1'
services:

  filaletter-website:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - ADMIN_HTTPS=1
      - REDIRECT_HTTPS=1
      - SSL_MODE=mixed
      - PHP_POOL_NAME="my-app_php"
    labels:
      caddy: filaletter.solutionforest.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy
      - front
      - back

networks:
  caddy:
    external: true
  front:
    driver: bridge
  back:
    driver: bridge